# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 600))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Windows/System32/GameSystemToastIcon.contrast-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1000, 600))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_map = QtWidgets.QWidget()
        self.tab_map.setObjectName("tab_map")
        self.m29 = QtWidgets.QPushButton(self.tab_map)
        self.m29.setGeometry(QtCore.QRect(620, 120, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m29.sizePolicy().hasHeightForWidth())
        self.m29.setSizePolicy(sizePolicy)
        self.m29.setText("")
        self.m29.setObjectName("m29")
        self.m09 = QtWidgets.QPushButton(self.tab_map)
        self.m09.setGeometry(QtCore.QRect(620, 40, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m09.sizePolicy().hasHeightForWidth())
        self.m09.setSizePolicy(sizePolicy)
        self.m09.setText("")
        self.m09.setObjectName("m09")
        self.m28 = QtWidgets.QPushButton(self.tab_map)
        self.m28.setGeometry(QtCore.QRect(580, 120, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m28.sizePolicy().hasHeightForWidth())
        self.m28.setSizePolicy(sizePolicy)
        self.m28.setText("")
        self.m28.setObjectName("m28")
        self.m30 = QtWidgets.QPushButton(self.tab_map)
        self.m30.setGeometry(QtCore.QRect(260, 160, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m30.sizePolicy().hasHeightForWidth())
        self.m30.setSizePolicy(sizePolicy)
        self.m30.setText("")
        self.m30.setObjectName("m30")
        self.m10 = QtWidgets.QPushButton(self.tab_map)
        self.m10.setGeometry(QtCore.QRect(260, 80, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m10.sizePolicy().hasHeightForWidth())
        self.m10.setSizePolicy(sizePolicy)
        self.m10.setText("")
        self.m10.setObjectName("m10")
        self.m31 = QtWidgets.QPushButton(self.tab_map)
        self.m31.setGeometry(QtCore.QRect(300, 160, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m31.sizePolicy().hasHeightForWidth())
        self.m31.setSizePolicy(sizePolicy)
        self.m31.setText("")
        self.m31.setObjectName("m31")
        self.m39 = QtWidgets.QPushButton(self.tab_map)
        self.m39.setGeometry(QtCore.QRect(620, 160, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m39.sizePolicy().hasHeightForWidth())
        self.m39.setSizePolicy(sizePolicy)
        self.m39.setText("")
        self.m39.setObjectName("m39")
        self.m44 = QtWidgets.QPushButton(self.tab_map)
        self.m44.setGeometry(QtCore.QRect(420, 200, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m44.sizePolicy().hasHeightForWidth())
        self.m44.setSizePolicy(sizePolicy)
        self.m44.setText("")
        self.m44.setObjectName("m44")
        self.m15 = QtWidgets.QPushButton(self.tab_map)
        self.m15.setGeometry(QtCore.QRect(460, 80, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m15.sizePolicy().hasHeightForWidth())
        self.m15.setSizePolicy(sizePolicy)
        self.m15.setText("")
        self.m15.setObjectName("m15")
        self.btn_delete_map = QtWidgets.QPushButton(self.tab_map)
        self.btn_delete_map.setGeometry(QtCore.QRect(200, 490, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_delete_map.sizePolicy().hasHeightForWidth())
        self.btn_delete_map.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.btn_delete_map.setFont(font)
        self.btn_delete_map.setObjectName("btn_delete_map")
        self.m42 = QtWidgets.QPushButton(self.tab_map)
        self.m42.setGeometry(QtCore.QRect(340, 200, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m42.sizePolicy().hasHeightForWidth())
        self.m42.setSizePolicy(sizePolicy)
        self.m42.setText("")
        self.m42.setObjectName("m42")
        self.m27 = QtWidgets.QPushButton(self.tab_map)
        self.m27.setGeometry(QtCore.QRect(540, 120, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m27.sizePolicy().hasHeightForWidth())
        self.m27.setSizePolicy(sizePolicy)
        self.m27.setText("")
        self.m27.setObjectName("m27")
        self.m43 = QtWidgets.QPushButton(self.tab_map)
        self.m43.setGeometry(QtCore.QRect(380, 200, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m43.sizePolicy().hasHeightForWidth())
        self.m43.setSizePolicy(sizePolicy)
        self.m43.setText("")
        self.m43.setObjectName("m43")
        self.m12 = QtWidgets.QPushButton(self.tab_map)
        self.m12.setGeometry(QtCore.QRect(340, 80, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m12.sizePolicy().hasHeightForWidth())
        self.m12.setSizePolicy(sizePolicy)
        self.m12.setText("")
        self.m12.setObjectName("m12")
        self.m22 = QtWidgets.QPushButton(self.tab_map)
        self.m22.setGeometry(QtCore.QRect(340, 120, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m22.sizePolicy().hasHeightForWidth())
        self.m22.setSizePolicy(sizePolicy)
        self.m22.setText("")
        self.m22.setObjectName("m22")
        self.m14 = QtWidgets.QPushButton(self.tab_map)
        self.m14.setGeometry(QtCore.QRect(420, 80, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m14.sizePolicy().hasHeightForWidth())
        self.m14.setSizePolicy(sizePolicy)
        self.m14.setText("")
        self.m14.setObjectName("m14")
        self.m49 = QtWidgets.QPushButton(self.tab_map)
        self.m49.setGeometry(QtCore.QRect(620, 200, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m49.sizePolicy().hasHeightForWidth())
        self.m49.setSizePolicy(sizePolicy)
        self.m49.setText("")
        self.m49.setObjectName("m49")
        self.m36 = QtWidgets.QPushButton(self.tab_map)
        self.m36.setGeometry(QtCore.QRect(500, 160, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m36.sizePolicy().hasHeightForWidth())
        self.m36.setSizePolicy(sizePolicy)
        self.m36.setText("")
        self.m36.setObjectName("m36")
        self.m18 = QtWidgets.QPushButton(self.tab_map)
        self.m18.setGeometry(QtCore.QRect(580, 80, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m18.sizePolicy().hasHeightForWidth())
        self.m18.setSizePolicy(sizePolicy)
        self.m18.setText("")
        self.m18.setObjectName("m18")
        self.m00 = QtWidgets.QPushButton(self.tab_map)
        self.m00.setGeometry(QtCore.QRect(260, 40, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m00.sizePolicy().hasHeightForWidth())
        self.m00.setSizePolicy(sizePolicy)
        self.m00.setText("")
        self.m00.setObjectName("m00")
        self.m03 = QtWidgets.QPushButton(self.tab_map)
        self.m03.setGeometry(QtCore.QRect(380, 40, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m03.sizePolicy().hasHeightForWidth())
        self.m03.setSizePolicy(sizePolicy)
        self.m03.setText("")
        self.m03.setObjectName("m03")
        self.m08 = QtWidgets.QPushButton(self.tab_map)
        self.m08.setGeometry(QtCore.QRect(580, 40, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m08.sizePolicy().hasHeightForWidth())
        self.m08.setSizePolicy(sizePolicy)
        self.m08.setText("")
        self.m08.setObjectName("m08")
        self.m33 = QtWidgets.QPushButton(self.tab_map)
        self.m33.setGeometry(QtCore.QRect(380, 160, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m33.sizePolicy().hasHeightForWidth())
        self.m33.setSizePolicy(sizePolicy)
        self.m33.setText("")
        self.m33.setObjectName("m33")
        self.m35 = QtWidgets.QPushButton(self.tab_map)
        self.m35.setGeometry(QtCore.QRect(460, 160, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m35.sizePolicy().hasHeightForWidth())
        self.m35.setSizePolicy(sizePolicy)
        self.m35.setText("")
        self.m35.setObjectName("m35")
        self.m25 = QtWidgets.QPushButton(self.tab_map)
        self.m25.setGeometry(QtCore.QRect(460, 120, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m25.sizePolicy().hasHeightForWidth())
        self.m25.setSizePolicy(sizePolicy)
        self.m25.setText("")
        self.m25.setObjectName("m25")
        self.btn_create_map = QtWidgets.QPushButton(self.tab_map)
        self.btn_create_map.setGeometry(QtCore.QRect(160, 490, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_create_map.sizePolicy().hasHeightForWidth())
        self.btn_create_map.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.btn_create_map.setFont(font)
        self.btn_create_map.setObjectName("btn_create_map")
        self.m48 = QtWidgets.QPushButton(self.tab_map)
        self.m48.setGeometry(QtCore.QRect(580, 200, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m48.sizePolicy().hasHeightForWidth())
        self.m48.setSizePolicy(sizePolicy)
        self.m48.setText("")
        self.m48.setObjectName("m48")
        self.m04 = QtWidgets.QPushButton(self.tab_map)
        self.m04.setGeometry(QtCore.QRect(420, 40, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m04.sizePolicy().hasHeightForWidth())
        self.m04.setSizePolicy(sizePolicy)
        self.m04.setText("")
        self.m04.setObjectName("m04")
        self.m46 = QtWidgets.QPushButton(self.tab_map)
        self.m46.setGeometry(QtCore.QRect(500, 200, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m46.sizePolicy().hasHeightForWidth())
        self.m46.setSizePolicy(sizePolicy)
        self.m46.setText("")
        self.m46.setObjectName("m46")
        self.m41 = QtWidgets.QPushButton(self.tab_map)
        self.m41.setGeometry(QtCore.QRect(300, 200, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m41.sizePolicy().hasHeightForWidth())
        self.m41.setSizePolicy(sizePolicy)
        self.m41.setText("")
        self.m41.setObjectName("m41")
        self.m21 = QtWidgets.QPushButton(self.tab_map)
        self.m21.setGeometry(QtCore.QRect(300, 120, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m21.sizePolicy().hasHeightForWidth())
        self.m21.setSizePolicy(sizePolicy)
        self.m21.setText("")
        self.m21.setObjectName("m21")
        self.lst_maps = QtWidgets.QListWidget(self.tab_map)
        self.lst_maps.setGeometry(QtCore.QRect(30, 20, 201, 461))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lst_maps.sizePolicy().hasHeightForWidth())
        self.lst_maps.setSizePolicy(sizePolicy)
        self.lst_maps.setObjectName("lst_maps")
        self.m17 = QtWidgets.QPushButton(self.tab_map)
        self.m17.setGeometry(QtCore.QRect(540, 80, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m17.sizePolicy().hasHeightForWidth())
        self.m17.setSizePolicy(sizePolicy)
        self.m17.setText("")
        self.m17.setObjectName("m17")
        self.m20 = QtWidgets.QPushButton(self.tab_map)
        self.m20.setGeometry(QtCore.QRect(260, 120, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m20.sizePolicy().hasHeightForWidth())
        self.m20.setSizePolicy(sizePolicy)
        self.m20.setText("")
        self.m20.setObjectName("m20")
        self.m45 = QtWidgets.QPushButton(self.tab_map)
        self.m45.setGeometry(QtCore.QRect(460, 200, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m45.sizePolicy().hasHeightForWidth())
        self.m45.setSizePolicy(sizePolicy)
        self.m45.setText("")
        self.m45.setObjectName("m45")
        self.m24 = QtWidgets.QPushButton(self.tab_map)
        self.m24.setGeometry(QtCore.QRect(420, 120, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m24.sizePolicy().hasHeightForWidth())
        self.m24.setSizePolicy(sizePolicy)
        self.m24.setText("")
        self.m24.setObjectName("m24")
        self.m37 = QtWidgets.QPushButton(self.tab_map)
        self.m37.setGeometry(QtCore.QRect(540, 160, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m37.sizePolicy().hasHeightForWidth())
        self.m37.setSizePolicy(sizePolicy)
        self.m37.setText("")
        self.m37.setObjectName("m37")
        self.m11 = QtWidgets.QPushButton(self.tab_map)
        self.m11.setGeometry(QtCore.QRect(300, 80, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m11.sizePolicy().hasHeightForWidth())
        self.m11.setSizePolicy(sizePolicy)
        self.m11.setText("")
        self.m11.setObjectName("m11")
        self.m01 = QtWidgets.QPushButton(self.tab_map)
        self.m01.setGeometry(QtCore.QRect(300, 40, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m01.sizePolicy().hasHeightForWidth())
        self.m01.setSizePolicy(sizePolicy)
        self.m01.setText("")
        self.m01.setObjectName("m01")
        self.m13 = QtWidgets.QPushButton(self.tab_map)
        self.m13.setGeometry(QtCore.QRect(380, 80, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m13.sizePolicy().hasHeightForWidth())
        self.m13.setSizePolicy(sizePolicy)
        self.m13.setText("")
        self.m13.setObjectName("m13")
        self.m23 = QtWidgets.QPushButton(self.tab_map)
        self.m23.setGeometry(QtCore.QRect(380, 120, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m23.sizePolicy().hasHeightForWidth())
        self.m23.setSizePolicy(sizePolicy)
        self.m23.setText("")
        self.m23.setObjectName("m23")
        self.m19 = QtWidgets.QPushButton(self.tab_map)
        self.m19.setGeometry(QtCore.QRect(620, 80, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m19.sizePolicy().hasHeightForWidth())
        self.m19.setSizePolicy(sizePolicy)
        self.m19.setText("")
        self.m19.setObjectName("m19")
        self.m16 = QtWidgets.QPushButton(self.tab_map)
        self.m16.setGeometry(QtCore.QRect(500, 80, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m16.sizePolicy().hasHeightForWidth())
        self.m16.setSizePolicy(sizePolicy)
        self.m16.setText("")
        self.m16.setObjectName("m16")
        self.m34 = QtWidgets.QPushButton(self.tab_map)
        self.m34.setGeometry(QtCore.QRect(420, 160, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m34.sizePolicy().hasHeightForWidth())
        self.m34.setSizePolicy(sizePolicy)
        self.m34.setText("")
        self.m34.setObjectName("m34")
        self.m32 = QtWidgets.QPushButton(self.tab_map)
        self.m32.setGeometry(QtCore.QRect(340, 160, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m32.sizePolicy().hasHeightForWidth())
        self.m32.setSizePolicy(sizePolicy)
        self.m32.setText("")
        self.m32.setObjectName("m32")
        self.m06 = QtWidgets.QPushButton(self.tab_map)
        self.m06.setGeometry(QtCore.QRect(500, 40, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m06.sizePolicy().hasHeightForWidth())
        self.m06.setSizePolicy(sizePolicy)
        self.m06.setText("")
        self.m06.setObjectName("m06")
        self.m02 = QtWidgets.QPushButton(self.tab_map)
        self.m02.setGeometry(QtCore.QRect(340, 40, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m02.sizePolicy().hasHeightForWidth())
        self.m02.setSizePolicy(sizePolicy)
        self.m02.setText("")
        self.m02.setObjectName("m02")
        self.m38 = QtWidgets.QPushButton(self.tab_map)
        self.m38.setGeometry(QtCore.QRect(580, 160, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m38.sizePolicy().hasHeightForWidth())
        self.m38.setSizePolicy(sizePolicy)
        self.m38.setText("")
        self.m38.setObjectName("m38")
        self.m26 = QtWidgets.QPushButton(self.tab_map)
        self.m26.setGeometry(QtCore.QRect(500, 120, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m26.sizePolicy().hasHeightForWidth())
        self.m26.setSizePolicy(sizePolicy)
        self.m26.setText("")
        self.m26.setObjectName("m26")
        self.m07 = QtWidgets.QPushButton(self.tab_map)
        self.m07.setGeometry(QtCore.QRect(540, 40, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m07.sizePolicy().hasHeightForWidth())
        self.m07.setSizePolicy(sizePolicy)
        self.m07.setText("")
        self.m07.setObjectName("m07")
        self.m47 = QtWidgets.QPushButton(self.tab_map)
        self.m47.setGeometry(QtCore.QRect(540, 200, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m47.sizePolicy().hasHeightForWidth())
        self.m47.setSizePolicy(sizePolicy)
        self.m47.setText("")
        self.m47.setObjectName("m47")
        self.m05 = QtWidgets.QPushButton(self.tab_map)
        self.m05.setGeometry(QtCore.QRect(460, 40, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m05.sizePolicy().hasHeightForWidth())
        self.m05.setSizePolicy(sizePolicy)
        self.m05.setText("")
        self.m05.setObjectName("m05")
        self.m40 = QtWidgets.QPushButton(self.tab_map)
        self.m40.setGeometry(QtCore.QRect(260, 200, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m40.sizePolicy().hasHeightForWidth())
        self.m40.setSizePolicy(sizePolicy)
        self.m40.setText("")
        self.m40.setObjectName("m40")
        self.m51 = QtWidgets.QPushButton(self.tab_map)
        self.m51.setGeometry(QtCore.QRect(300, 240, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m51.sizePolicy().hasHeightForWidth())
        self.m51.setSizePolicy(sizePolicy)
        self.m51.setText("")
        self.m51.setObjectName("m51")
        self.m55 = QtWidgets.QPushButton(self.tab_map)
        self.m55.setGeometry(QtCore.QRect(460, 240, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m55.sizePolicy().hasHeightForWidth())
        self.m55.setSizePolicy(sizePolicy)
        self.m55.setText("")
        self.m55.setObjectName("m55")
        self.m57 = QtWidgets.QPushButton(self.tab_map)
        self.m57.setGeometry(QtCore.QRect(540, 240, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m57.sizePolicy().hasHeightForWidth())
        self.m57.setSizePolicy(sizePolicy)
        self.m57.setText("")
        self.m57.setObjectName("m57")
        self.m52 = QtWidgets.QPushButton(self.tab_map)
        self.m52.setGeometry(QtCore.QRect(340, 240, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m52.sizePolicy().hasHeightForWidth())
        self.m52.setSizePolicy(sizePolicy)
        self.m52.setText("")
        self.m52.setObjectName("m52")
        self.m53 = QtWidgets.QPushButton(self.tab_map)
        self.m53.setGeometry(QtCore.QRect(380, 240, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m53.sizePolicy().hasHeightForWidth())
        self.m53.setSizePolicy(sizePolicy)
        self.m53.setText("")
        self.m53.setObjectName("m53")
        self.m54 = QtWidgets.QPushButton(self.tab_map)
        self.m54.setGeometry(QtCore.QRect(420, 240, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m54.sizePolicy().hasHeightForWidth())
        self.m54.setSizePolicy(sizePolicy)
        self.m54.setText("")
        self.m54.setObjectName("m54")
        self.m58 = QtWidgets.QPushButton(self.tab_map)
        self.m58.setGeometry(QtCore.QRect(580, 240, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m58.sizePolicy().hasHeightForWidth())
        self.m58.setSizePolicy(sizePolicy)
        self.m58.setText("")
        self.m58.setObjectName("m58")
        self.m59 = QtWidgets.QPushButton(self.tab_map)
        self.m59.setGeometry(QtCore.QRect(620, 240, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m59.sizePolicy().hasHeightForWidth())
        self.m59.setSizePolicy(sizePolicy)
        self.m59.setText("")
        self.m59.setObjectName("m59")
        self.m56 = QtWidgets.QPushButton(self.tab_map)
        self.m56.setGeometry(QtCore.QRect(500, 240, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m56.sizePolicy().hasHeightForWidth())
        self.m56.setSizePolicy(sizePolicy)
        self.m56.setText("")
        self.m56.setObjectName("m56")
        self.m50 = QtWidgets.QPushButton(self.tab_map)
        self.m50.setGeometry(QtCore.QRect(260, 240, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m50.sizePolicy().hasHeightForWidth())
        self.m50.setSizePolicy(sizePolicy)
        self.m50.setText("")
        self.m50.setObjectName("m50")
        self.m61 = QtWidgets.QPushButton(self.tab_map)
        self.m61.setGeometry(QtCore.QRect(300, 280, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m61.sizePolicy().hasHeightForWidth())
        self.m61.setSizePolicy(sizePolicy)
        self.m61.setText("")
        self.m61.setObjectName("m61")
        self.m65 = QtWidgets.QPushButton(self.tab_map)
        self.m65.setGeometry(QtCore.QRect(460, 280, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m65.sizePolicy().hasHeightForWidth())
        self.m65.setSizePolicy(sizePolicy)
        self.m65.setText("")
        self.m65.setObjectName("m65")
        self.m62 = QtWidgets.QPushButton(self.tab_map)
        self.m62.setGeometry(QtCore.QRect(340, 280, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m62.sizePolicy().hasHeightForWidth())
        self.m62.setSizePolicy(sizePolicy)
        self.m62.setText("")
        self.m62.setObjectName("m62")
        self.m64 = QtWidgets.QPushButton(self.tab_map)
        self.m64.setGeometry(QtCore.QRect(420, 280, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m64.sizePolicy().hasHeightForWidth())
        self.m64.setSizePolicy(sizePolicy)
        self.m64.setText("")
        self.m64.setObjectName("m64")
        self.m68 = QtWidgets.QPushButton(self.tab_map)
        self.m68.setGeometry(QtCore.QRect(580, 280, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m68.sizePolicy().hasHeightForWidth())
        self.m68.setSizePolicy(sizePolicy)
        self.m68.setText("")
        self.m68.setObjectName("m68")
        self.m66 = QtWidgets.QPushButton(self.tab_map)
        self.m66.setGeometry(QtCore.QRect(500, 280, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m66.sizePolicy().hasHeightForWidth())
        self.m66.setSizePolicy(sizePolicy)
        self.m66.setText("")
        self.m66.setObjectName("m66")
        self.m67 = QtWidgets.QPushButton(self.tab_map)
        self.m67.setGeometry(QtCore.QRect(540, 280, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m67.sizePolicy().hasHeightForWidth())
        self.m67.setSizePolicy(sizePolicy)
        self.m67.setText("")
        self.m67.setObjectName("m67")
        self.m60 = QtWidgets.QPushButton(self.tab_map)
        self.m60.setGeometry(QtCore.QRect(260, 280, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m60.sizePolicy().hasHeightForWidth())
        self.m60.setSizePolicy(sizePolicy)
        self.m60.setText("")
        self.m60.setObjectName("m60")
        self.m63 = QtWidgets.QPushButton(self.tab_map)
        self.m63.setGeometry(QtCore.QRect(380, 280, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m63.sizePolicy().hasHeightForWidth())
        self.m63.setSizePolicy(sizePolicy)
        self.m63.setText("")
        self.m63.setObjectName("m63")
        self.m69 = QtWidgets.QPushButton(self.tab_map)
        self.m69.setGeometry(QtCore.QRect(620, 280, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m69.sizePolicy().hasHeightForWidth())
        self.m69.setSizePolicy(sizePolicy)
        self.m69.setText("")
        self.m69.setObjectName("m69")
        self.m70 = QtWidgets.QPushButton(self.tab_map)
        self.m70.setGeometry(QtCore.QRect(260, 320, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m70.sizePolicy().hasHeightForWidth())
        self.m70.setSizePolicy(sizePolicy)
        self.m70.setText("")
        self.m70.setObjectName("m70")
        self.m75 = QtWidgets.QPushButton(self.tab_map)
        self.m75.setGeometry(QtCore.QRect(460, 320, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m75.sizePolicy().hasHeightForWidth())
        self.m75.setSizePolicy(sizePolicy)
        self.m75.setText("")
        self.m75.setFlat(False)
        self.m75.setObjectName("m75")
        self.m78 = QtWidgets.QPushButton(self.tab_map)
        self.m78.setGeometry(QtCore.QRect(580, 320, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m78.sizePolicy().hasHeightForWidth())
        self.m78.setSizePolicy(sizePolicy)
        self.m78.setText("")
        self.m78.setObjectName("m78")
        self.m79 = QtWidgets.QPushButton(self.tab_map)
        self.m79.setGeometry(QtCore.QRect(620, 320, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m79.sizePolicy().hasHeightForWidth())
        self.m79.setSizePolicy(sizePolicy)
        self.m79.setText("")
        self.m79.setObjectName("m79")
        self.m73 = QtWidgets.QPushButton(self.tab_map)
        self.m73.setGeometry(QtCore.QRect(380, 320, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m73.sizePolicy().hasHeightForWidth())
        self.m73.setSizePolicy(sizePolicy)
        self.m73.setText("")
        self.m73.setObjectName("m73")
        self.m71 = QtWidgets.QPushButton(self.tab_map)
        self.m71.setGeometry(QtCore.QRect(300, 320, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m71.sizePolicy().hasHeightForWidth())
        self.m71.setSizePolicy(sizePolicy)
        self.m71.setText("")
        self.m71.setObjectName("m71")
        self.m77 = QtWidgets.QPushButton(self.tab_map)
        self.m77.setGeometry(QtCore.QRect(540, 320, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m77.sizePolicy().hasHeightForWidth())
        self.m77.setSizePolicy(sizePolicy)
        self.m77.setText("")
        self.m77.setFlat(False)
        self.m77.setObjectName("m77")
        self.m74 = QtWidgets.QPushButton(self.tab_map)
        self.m74.setGeometry(QtCore.QRect(420, 320, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m74.sizePolicy().hasHeightForWidth())
        self.m74.setSizePolicy(sizePolicy)
        self.m74.setText("")
        self.m74.setObjectName("m74")
        self.m76 = QtWidgets.QPushButton(self.tab_map)
        self.m76.setGeometry(QtCore.QRect(500, 320, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m76.sizePolicy().hasHeightForWidth())
        self.m76.setSizePolicy(sizePolicy)
        self.m76.setText("")
        self.m76.setObjectName("m76")
        self.m72 = QtWidgets.QPushButton(self.tab_map)
        self.m72.setGeometry(QtCore.QRect(340, 320, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m72.sizePolicy().hasHeightForWidth())
        self.m72.setSizePolicy(sizePolicy)
        self.m72.setText("")
        self.m72.setObjectName("m72")
        self.spinBox = QtWidgets.QSpinBox(self.tab_map)
        self.spinBox.setGeometry(QtCore.QRect(300, 490, 42, 22))
        self.spinBox.setMinimum(3)
        self.spinBox.setMaximum(10)
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.tab_map)
        self.spinBox_2.setGeometry(QtCore.QRect(400, 490, 42, 22))
        self.spinBox_2.setMinimum(3)
        self.spinBox_2.setMaximum(10)
        self.spinBox_2.setObjectName("spinBox_2")
        self.label = QtWidgets.QLabel(self.tab_map)
        self.label.setGeometry(QtCore.QRect(270, 495, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_map)
        self.label_2.setGeometry(QtCore.QRect(360, 495, 47, 13))
        self.label_2.setObjectName("label_2")
        self.radioButton = QtWidgets.QRadioButton(self.tab_map)
        self.radioButton.setGeometry(QtCore.QRect(470, 480, 82, 17))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_map)
        self.radioButton_2.setGeometry(QtCore.QRect(470, 500, 82, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.m29.raise_()
        self.m09.raise_()
        self.m28.raise_()
        self.m30.raise_()
        self.m10.raise_()
        self.m31.raise_()
        self.m39.raise_()
        self.m44.raise_()
        self.m15.raise_()
        self.m42.raise_()
        self.m27.raise_()
        self.m43.raise_()
        self.m12.raise_()
        self.m22.raise_()
        self.m14.raise_()
        self.m49.raise_()
        self.m36.raise_()
        self.m18.raise_()
        self.m00.raise_()
        self.m03.raise_()
        self.m08.raise_()
        self.m33.raise_()
        self.m35.raise_()
        self.m25.raise_()
        self.btn_create_map.raise_()
        self.m48.raise_()
        self.m04.raise_()
        self.m46.raise_()
        self.m41.raise_()
        self.m21.raise_()
        self.lst_maps.raise_()
        self.m17.raise_()
        self.m20.raise_()
        self.m45.raise_()
        self.m24.raise_()
        self.m37.raise_()
        self.m11.raise_()
        self.m01.raise_()
        self.m13.raise_()
        self.m23.raise_()
        self.m19.raise_()
        self.m16.raise_()
        self.m34.raise_()
        self.m32.raise_()
        self.m06.raise_()
        self.m02.raise_()
        self.m38.raise_()
        self.m26.raise_()
        self.m07.raise_()
        self.m47.raise_()
        self.m05.raise_()
        self.m40.raise_()
        self.btn_delete_map.raise_()
        self.m51.raise_()
        self.m55.raise_()
        self.m57.raise_()
        self.m52.raise_()
        self.m53.raise_()
        self.m54.raise_()
        self.m58.raise_()
        self.m59.raise_()
        self.m56.raise_()
        self.m50.raise_()
        self.m61.raise_()
        self.m65.raise_()
        self.m62.raise_()
        self.m64.raise_()
        self.m68.raise_()
        self.m66.raise_()
        self.m67.raise_()
        self.m60.raise_()
        self.m63.raise_()
        self.m69.raise_()
        self.m70.raise_()
        self.m75.raise_()
        self.m78.raise_()
        self.m79.raise_()
        self.m73.raise_()
        self.m71.raise_()
        self.m77.raise_()
        self.m74.raise_()
        self.m76.raise_()
        self.m72.raise_()
        self.spinBox.raise_()
        self.spinBox_2.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.radioButton.raise_()
        self.radioButton_2.raise_()
        self.tabWidget.addTab(self.tab_map, "")
        self.tab_equipment = QtWidgets.QWidget()
        self.tab_equipment.setObjectName("tab_equipment")
        self.lst_equipment = QtWidgets.QListWidget(self.tab_equipment)
        self.lst_equipment.setGeometry(QtCore.QRect(30, 20, 201, 461))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lst_equipment.sizePolicy().hasHeightForWidth())
        self.lst_equipment.setSizePolicy(sizePolicy)
        self.lst_equipment.setObjectName("lst_equipment")
        self.btn_delete_equipment = QtWidgets.QPushButton(self.tab_equipment)
        self.btn_delete_equipment.setGeometry(QtCore.QRect(200, 490, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_delete_equipment.sizePolicy().hasHeightForWidth())
        self.btn_delete_equipment.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.btn_delete_equipment.setFont(font)
        self.btn_delete_equipment.setObjectName("btn_delete_equipment")
        self.btn_create_equipment = QtWidgets.QPushButton(self.tab_equipment)
        self.btn_create_equipment.setGeometry(QtCore.QRect(160, 490, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_create_equipment.sizePolicy().hasHeightForWidth())
        self.btn_create_equipment.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.btn_create_equipment.setFont(font)
        self.btn_create_equipment.setObjectName("btn_create_equipment")
        self.txt_equipment_name = QtWidgets.QLineEdit(self.tab_equipment)
        self.txt_equipment_name.setGeometry(QtCore.QRect(260, 30, 361, 20))
        self.txt_equipment_name.setClearButtonEnabled(False)
        self.txt_equipment_name.setObjectName("txt_equipment_name")
        self.txt_equipment_size = QtWidgets.QLineEdit(self.tab_equipment)
        self.txt_equipment_size.setGeometry(QtCore.QRect(630, 30, 61, 20))
        self.txt_equipment_size.setClearButtonEnabled(False)
        self.txt_equipment_size.setObjectName("txt_equipment_size")
        self.cmb_equipment_type = QtWidgets.QComboBox(self.tab_equipment)
        self.cmb_equipment_type.setGeometry(QtCore.QRect(630, 60, 141, 22))
        self.cmb_equipment_type.setObjectName("cmb_equipment_type")
        self.txt_flavor_equipment = QtWidgets.QPlainTextEdit(self.tab_equipment)
        self.txt_flavor_equipment.setGeometry(QtCore.QRect(260, 60, 361, 51))
        self.txt_flavor_equipment.setReadOnly(False)
        self.txt_flavor_equipment.setObjectName("txt_flavor_equipment")
        self.chk_stat1_equipment = QtWidgets.QCheckBox(self.tab_equipment)
        self.chk_stat1_equipment.setGeometry(QtCore.QRect(260, 150, 16, 17))
        self.chk_stat1_equipment.setText("")
        self.chk_stat1_equipment.setObjectName("chk_stat1_equipment")
        self.chk_stat2_equipment = QtWidgets.QCheckBox(self.tab_equipment)
        self.chk_stat2_equipment.setGeometry(QtCore.QRect(260, 180, 16, 17))
        self.chk_stat2_equipment.setText("")
        self.chk_stat2_equipment.setObjectName("chk_stat2_equipment")
        self.chk_stat3_equipment = QtWidgets.QCheckBox(self.tab_equipment)
        self.chk_stat3_equipment.setGeometry(QtCore.QRect(260, 210, 16, 17))
        self.chk_stat3_equipment.setText("")
        self.chk_stat3_equipment.setObjectName("chk_stat3_equipment")
        self.chk_stat4_equipment = QtWidgets.QCheckBox(self.tab_equipment)
        self.chk_stat4_equipment.setGeometry(QtCore.QRect(260, 240, 16, 17))
        self.chk_stat4_equipment.setText("")
        self.chk_stat4_equipment.setObjectName("chk_stat4_equipment")
        self.chk_stat5_equipment = QtWidgets.QCheckBox(self.tab_equipment)
        self.chk_stat5_equipment.setGeometry(QtCore.QRect(260, 270, 16, 17))
        self.chk_stat5_equipment.setText("")
        self.chk_stat5_equipment.setObjectName("chk_stat5_equipment")
        self.chk_stat6_equipment = QtWidgets.QCheckBox(self.tab_equipment)
        self.chk_stat6_equipment.setGeometry(QtCore.QRect(260, 300, 16, 17))
        self.chk_stat6_equipment.setText("")
        self.chk_stat6_equipment.setObjectName("chk_stat6_equipment")
        self.chk_stat7_equipment = QtWidgets.QCheckBox(self.tab_equipment)
        self.chk_stat7_equipment.setGeometry(QtCore.QRect(260, 330, 16, 17))
        self.chk_stat7_equipment.setText("")
        self.chk_stat7_equipment.setObjectName("chk_stat7_equipment")
        self.chk_stat8_equipment = QtWidgets.QCheckBox(self.tab_equipment)
        self.chk_stat8_equipment.setGeometry(QtCore.QRect(260, 360, 16, 17))
        self.chk_stat8_equipment.setText("")
        self.chk_stat8_equipment.setObjectName("chk_stat8_equipment")
        self.lst_stat1_equipment = QtWidgets.QComboBox(self.tab_equipment)
        self.lst_stat1_equipment.setGeometry(QtCore.QRect(280, 150, 141, 22))
        self.lst_stat1_equipment.setObjectName("lst_stat1_equipment")
        self.lst_stat2_equipment = QtWidgets.QComboBox(self.tab_equipment)
        self.lst_stat2_equipment.setGeometry(QtCore.QRect(280, 180, 141, 22))
        self.lst_stat2_equipment.setObjectName("lst_stat2_equipment")
        self.lst_stat3_equipment = QtWidgets.QComboBox(self.tab_equipment)
        self.lst_stat3_equipment.setGeometry(QtCore.QRect(280, 210, 141, 22))
        self.lst_stat3_equipment.setObjectName("lst_stat3_equipment")
        self.lst_stat4_equipment = QtWidgets.QComboBox(self.tab_equipment)
        self.lst_stat4_equipment.setGeometry(QtCore.QRect(280, 240, 141, 22))
        self.lst_stat4_equipment.setObjectName("lst_stat4_equipment")
        self.lst_stat5_equipment = QtWidgets.QComboBox(self.tab_equipment)
        self.lst_stat5_equipment.setGeometry(QtCore.QRect(280, 270, 141, 22))
        self.lst_stat5_equipment.setObjectName("lst_stat5_equipment")
        self.lst_stat6_equipment = QtWidgets.QComboBox(self.tab_equipment)
        self.lst_stat6_equipment.setGeometry(QtCore.QRect(280, 300, 141, 22))
        self.lst_stat6_equipment.setObjectName("lst_stat6_equipment")
        self.lst_stat7_equipment = QtWidgets.QComboBox(self.tab_equipment)
        self.lst_stat7_equipment.setGeometry(QtCore.QRect(280, 330, 141, 22))
        self.lst_stat7_equipment.setObjectName("lst_stat7_equipment")
        self.lst_stat8_equipment = QtWidgets.QComboBox(self.tab_equipment)
        self.lst_stat8_equipment.setGeometry(QtCore.QRect(280, 360, 141, 22))
        self.lst_stat8_equipment.setObjectName("lst_stat8_equipment")
        self.txt_stat1_equipment = QtWidgets.QLineEdit(self.tab_equipment)
        self.txt_stat1_equipment.setGeometry(QtCore.QRect(430, 150, 41, 20))
        self.txt_stat1_equipment.setObjectName("txt_stat1_equipment")
        self.txt_stat2_equipment = QtWidgets.QLineEdit(self.tab_equipment)
        self.txt_stat2_equipment.setGeometry(QtCore.QRect(430, 180, 41, 20))
        self.txt_stat2_equipment.setObjectName("txt_stat2_equipment")
        self.txt_stat3_equipment = QtWidgets.QLineEdit(self.tab_equipment)
        self.txt_stat3_equipment.setGeometry(QtCore.QRect(430, 210, 41, 20))
        self.txt_stat3_equipment.setObjectName("txt_stat3_equipment")
        self.txt_stat4_equipment = QtWidgets.QLineEdit(self.tab_equipment)
        self.txt_stat4_equipment.setGeometry(QtCore.QRect(430, 240, 41, 20))
        self.txt_stat4_equipment.setObjectName("txt_stat4_equipment")
        self.txt_stat5_equipment = QtWidgets.QLineEdit(self.tab_equipment)
        self.txt_stat5_equipment.setGeometry(QtCore.QRect(430, 270, 41, 20))
        self.txt_stat5_equipment.setObjectName("txt_stat5_equipment")
        self.txt_stat6_equipment = QtWidgets.QLineEdit(self.tab_equipment)
        self.txt_stat6_equipment.setGeometry(QtCore.QRect(430, 300, 41, 20))
        self.txt_stat6_equipment.setObjectName("txt_stat6_equipment")
        self.txt_stat7_equipment = QtWidgets.QLineEdit(self.tab_equipment)
        self.txt_stat7_equipment.setGeometry(QtCore.QRect(430, 330, 41, 20))
        self.txt_stat7_equipment.setObjectName("txt_stat7_equipment")
        self.txt_stat8_equipment = QtWidgets.QLineEdit(self.tab_equipment)
        self.txt_stat8_equipment.setGeometry(QtCore.QRect(430, 360, 41, 20))
        self.txt_stat8_equipment.setObjectName("txt_stat8_equipment")
        self.lbl_stats = QtWidgets.QLabel(self.tab_equipment)
        self.lbl_stats.setGeometry(QtCore.QRect(260, 130, 47, 13))
        self.lbl_stats.setObjectName("lbl_stats")
        self.cmb_equipment_rarity = QtWidgets.QComboBox(self.tab_equipment)
        self.cmb_equipment_rarity.setGeometry(QtCore.QRect(630, 90, 141, 22))
        self.cmb_equipment_rarity.setObjectName("cmb_equipment_rarity")
        self.lbl_effects = QtWidgets.QLabel(self.tab_equipment)
        self.lbl_effects.setGeometry(QtCore.QRect(500, 130, 47, 13))
        self.lbl_effects.setObjectName("lbl_effects")
        self.chk_effect1_equipment = QtWidgets.QCheckBox(self.tab_equipment)
        self.chk_effect1_equipment.setGeometry(QtCore.QRect(500, 150, 16, 17))
        self.chk_effect1_equipment.setText("")
        self.chk_effect1_equipment.setObjectName("chk_effect1_equipment")
        self.lst_effect1_equipment = QtWidgets.QComboBox(self.tab_equipment)
        self.lst_effect1_equipment.setGeometry(QtCore.QRect(520, 150, 291, 22))
        self.lst_effect1_equipment.setObjectName("lst_effect1_equipment")
        self.txt_effect1_equipment_1 = QtWidgets.QLineEdit(self.tab_equipment)
        self.txt_effect1_equipment_1.setGeometry(QtCore.QRect(820, 150, 41, 20))
        self.txt_effect1_equipment_1.setObjectName("txt_effect1_equipment_1")
        self.txt_effect1_equipment_2 = QtWidgets.QLineEdit(self.tab_equipment)
        self.txt_effect1_equipment_2.setGeometry(QtCore.QRect(870, 150, 41, 20))
        self.txt_effect1_equipment_2.setObjectName("txt_effect1_equipment_2")
        self.txt_equipment_gold = QtWidgets.QLineEdit(self.tab_equipment)
        self.txt_equipment_gold.setGeometry(QtCore.QRect(700, 30, 71, 20))
        self.txt_equipment_gold.setClearButtonEnabled(False)
        self.txt_equipment_gold.setObjectName("txt_equipment_gold")
        self.txt_effect1_equipment_3 = QtWidgets.QLineEdit(self.tab_equipment)
        self.txt_effect1_equipment_3.setGeometry(QtCore.QRect(920, 150, 41, 20))
        self.txt_effect1_equipment_3.setObjectName("txt_effect1_equipment_3")
        self.chk_effect2_equipment = QtWidgets.QCheckBox(self.tab_equipment)
        self.chk_effect2_equipment.setGeometry(QtCore.QRect(500, 180, 16, 17))
        self.chk_effect2_equipment.setText("")
        self.chk_effect2_equipment.setObjectName("chk_effect2_equipment")
        self.chk_effect3_equipment = QtWidgets.QCheckBox(self.tab_equipment)
        self.chk_effect3_equipment.setGeometry(QtCore.QRect(500, 210, 16, 17))
        self.chk_effect3_equipment.setText("")
        self.chk_effect3_equipment.setObjectName("chk_effect3_equipment")
        self.lst_effect2_equipment = QtWidgets.QComboBox(self.tab_equipment)
        self.lst_effect2_equipment.setGeometry(QtCore.QRect(520, 180, 291, 22))
        self.lst_effect2_equipment.setObjectName("lst_effect2_equipment")
        self.lst_effect3_equipment = QtWidgets.QComboBox(self.tab_equipment)
        self.lst_effect3_equipment.setGeometry(QtCore.QRect(520, 210, 291, 22))
        self.lst_effect3_equipment.setObjectName("lst_effect3_equipment")
        self.txt_effect2_equipment_2 = QtWidgets.QLineEdit(self.tab_equipment)
        self.txt_effect2_equipment_2.setGeometry(QtCore.QRect(870, 180, 41, 20))
        self.txt_effect2_equipment_2.setObjectName("txt_effect2_equipment_2")
        self.txt_effect2_equipment_3 = QtWidgets.QLineEdit(self.tab_equipment)
        self.txt_effect2_equipment_3.setGeometry(QtCore.QRect(920, 180, 41, 20))
        self.txt_effect2_equipment_3.setObjectName("txt_effect2_equipment_3")
        self.txt_effect2_equipment_1 = QtWidgets.QLineEdit(self.tab_equipment)
        self.txt_effect2_equipment_1.setGeometry(QtCore.QRect(820, 180, 41, 20))
        self.txt_effect2_equipment_1.setObjectName("txt_effect2_equipment_1")
        self.txt_effect3_equipment_1 = QtWidgets.QLineEdit(self.tab_equipment)
        self.txt_effect3_equipment_1.setGeometry(QtCore.QRect(820, 210, 41, 20))
        self.txt_effect3_equipment_1.setObjectName("txt_effect3_equipment_1")
        self.txt_effect3_equipment_2 = QtWidgets.QLineEdit(self.tab_equipment)
        self.txt_effect3_equipment_2.setGeometry(QtCore.QRect(870, 210, 41, 20))
        self.txt_effect3_equipment_2.setObjectName("txt_effect3_equipment_2")
        self.txt_effect3_equipment_3 = QtWidgets.QLineEdit(self.tab_equipment)
        self.txt_effect3_equipment_3.setGeometry(QtCore.QRect(920, 210, 41, 20))
        self.txt_effect3_equipment_3.setObjectName("txt_effect3_equipment_3")
        self.tabWidget.addTab(self.tab_equipment, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_dat = QtWidgets.QAction(MainWindow)
        self.actionLoad_dat.setObjectName("actionLoad_dat")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_dat = QtWidgets.QAction(MainWindow)
        self.actionSave_dat.setObjectName("actionSave_dat")
        self.actionGithub_page = QtWidgets.QAction(MainWindow)
        self.actionGithub_page.setObjectName("actionGithub_page")
        self.menuFile.addAction(self.actionLoad_dat)
        self.menuFile.addAction(self.actionSave_dat)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionGithub_page)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.lst_maps.setCurrentRow(-1)
        self.lst_equipment.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "IFASP Editor"))
        self.btn_delete_map.setText(_translate("MainWindow", "-"))
        self.btn_create_map.setText(_translate("MainWindow", "+"))
        self.label.setText(_translate("MainWindow", "Width"))
        self.label_2.setText(_translate("MainWindow", "Height"))
        self.radioButton.setText(_translate("MainWindow", "Terrain mode"))
        self.radioButton_2.setText(_translate("MainWindow", "Entity mode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_map), _translate("MainWindow", "Map editor"))
        self.btn_delete_equipment.setText(_translate("MainWindow", "-"))
        self.btn_create_equipment.setText(_translate("MainWindow", "+"))
        self.txt_equipment_name.setPlaceholderText(_translate("MainWindow", "Name"))
        self.txt_equipment_size.setPlaceholderText(_translate("MainWindow", "Size"))
        self.txt_flavor_equipment.setPlaceholderText(_translate("MainWindow", "Flavor text..."))
        self.lbl_stats.setText(_translate("MainWindow", "Stats"))
        self.lbl_effects.setText(_translate("MainWindow", "Effects"))
        self.txt_equipment_gold.setPlaceholderText(_translate("MainWindow", "Gold"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_equipment), _translate("MainWindow", "Equipment editor"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionLoad_dat.setText(_translate("MainWindow", "Load .dat"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSave_dat.setText(_translate("MainWindow", "Save .dat"))
        self.actionGithub_page.setText(_translate("MainWindow", "Github page"))

